###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: laravel-angular-reactnative-fullstack-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=math3036
        - MYSQL_DATABASE=laravel-angular-reactnative-gestao
        - MYSQL_USER=laravel-angular-reactnative-gestao
        - MYSQL_PASSWORD=math3036
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-angular-reactnative-fullstack-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laravel-angular-reactnative-fullstack-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

